### ISSUE TITLE
Implement linear indexing `seti` `geti`

### ISSUE THREAD

**Issue by mattsignorelli** [bmad-sim/GTPSA.jl#103]
**TO-DO**
- [ ] Change sparse monomial indexing to require tuple/vector for variables part
- [ ] Change monomial indexing to single vector/tuple of integer orders
- [ ] Implement linear indexing with single int

Only interfaces monomial and sparse monomial indexing are currently implemented, however it would be useful to have linear indexing for speed in simple settings (e.g. subtracting the identity from the linear part of a map)

**Comment by mattsignorelli** [comment]
The reason is because monomial and sparse monomial indexing require allocating an array to pass to C, whereas linear indexing does not. How to implement this is tricky though because 

`t[int,..]`, `t[int,int,...]` is already used for monomial indexing

**Comment by mattsignorelli** [comment]
@DavidSagan do you have any preference? I am leaning towards changing monomial indexing to be a nested array

**Comment by mattsignorelli** [comment]
- [ ] Change sparse monomial indexing to require tuple/vector for variables part
- [ ] For sparse monomial indexing remove `params` kwarg, instead just have optional second vector/tuple of pairs
- [ ] Change monomial indexing to single vector of integer orders
- [ ] Implement linear indexing with single int

**Comment by mattsignorelli** [comment]
@DavidSagan For sparse monomial indexing, I think I'd like to keep the `params` kwarg, because if its not there and someone would like to index a monomial with only parameters (eg. `k_2^3k_3`), then you'd have to do `t[ [], [2=>3, 3=>1] ]` instead of `t[params=[2=>3, 3=>1]]`. Any thoughts?
