### ISSUE TITLE
Long term to-do

### ISSUE THREAD

**Issue by mattsignorelli** [bmad-sim/GTPSA.jl#96]
Rewrite of library entirely in Julia:
- [ ] Should work for arbitrary number types, e.g `TPS64 = TPS{Float64}`, `TPS{Float128}`, etc (not only Float64 and ComplexF64). This also opens up allowing symbolics as TPS 
- [ ] TPSs should be immutable structs
- [ ] Adopt [Base `Complex`](https://github.com/JuliaLang/julia/blob/0588cd407862715e1f0544703d69cfb5d653681c/base/complex.jl#L4C1-L5C1) definition (so `ComplexTPS64 = Complex{TPS64}`)

**Comment by mattsignorelli** [comment]
New TPS implementation support all of this/has it already, rewrite will be much simpler

**Comment by mattsignorelli** [comment]
Immutability of TPS struct could still be considered
